# Author: André Bento
version: 1

disable_existing_loggers: false

root:
  level: INFO
  handlers: [console, info_file_handler, debug_file_handler, error_file_handler]

loggers:
  ErrorModuleLogger:
    level: ERROR
    handlers: [console]
    propagate: no

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

formatters:
  standard:
    format: "%(asctime)s; %(name)s; %(levelname)s; %(module)s; %(funcName)s(); %(message)s"
  error:
    format: "%(asctime)s; %(name)s; %(levelname)s; %(module)s; %(filename)s; %(funcName)s(); %(lineno)d; %(message)s"
